### ISSUE TITLE
Why we need register.go?

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/recordio#2]
I don't see how we use https://github.com/PaddlePaddle/recordio/blob/master/c/register.go

**Comment by helinwang** [comment]
It's related to the problem that now cgo don't allow pass Go pointer to C. A solution is to pass a integer key to C while saving a map from key to pointer in Go side.
Please see: https://github.com/golang/go/wiki/cgo#function-variables

**Comment by helinwang** [comment]
Please reopen if you are unclear or have more question :)
